"""Hold the wall clock still, so that "identical conditions" can actually be identical.

The clock arm as first written was broken, and the benchmark is what showed it. A test
asserting `int(time.time()) % 2 == 0` flipped in the **baseline** and was reported as
nondeterministic - the one arm that was supposed to be the control.

Of course it did. Running a suite seven times takes seven different moments. The baseline
can hold the seed still and the order still; it cannot hold the clock still, because the
clock is what running things costs. So every clock-dependent test in every repository would
be attributed to nondeterminism, confidently and wrongly, and the clock arm would find
nothing that the baseline had not already claimed.

The fix turns the clock into a variable like the others: **freeze it in every arm**, and vary
the frozen instant only in the clock arm. Then the baseline really is identical conditions,
and a test that is stable at one instant and unstable across several depends on the date.

Frozen: `time.time`, `time.localtime`, `time.gmtime`, `time.strftime`, `datetime.now`,
`datetime.utcnow`, `date.today`.

**Not** frozen: `time.monotonic` and `time.perf_counter`. Those measure elapsed time, not
dates. Freezing them makes every `while time.monotonic() < deadline` loop run forever, and a
tool that hangs the suite it was asked to diagnose is worse than no tool.

The instants below are chosen, not random. Second parity, midnight, a month boundary, a year
boundary, a leap day and a US daylight-saving repeat - the dates that real calendar code
actually gets wrong.
"""

from __future__ import annotations

import atexit
import shutil
import tempfile
from datetime import datetime
from pathlib import Path

PLUGIN_NAME = "fd_freeze_clock"
ENV_VAR = "FD_FREEZE_EPOCH"


def _at(y: int, mo: int, d: int, h: int, mi: int, s: int) -> float:
    """An instant, named in **local** time.

    Not UTC, and the difference matters. These dates are chosen to sit on boundaries -
    midnight, a month end, a leap day - and a boundary is only a boundary in one timezone.
    Pinned to UTC on a UTC+5 machine, the leap-day and month-boundary instants below both
    land on the local afternoon of the same ordinary day, five hours from any edge, and the
    arm quietly stops testing what it was written to test.

    The suite under investigation reads the clock in local time, so the edges are placed
    where that suite will see them.
    """
    return datetime(y, mo, d, h, mi, s).timestamp()


#: The instant every arm but the clock arm is pinned to. Even second, mid-month, mid-day -
#: deliberately unremarkable, so the baseline is not itself sitting on an edge case.
BASELINE_EPOCH = _at(2024, 6, 12, 12, 0, 0)

#: What the clock arm walks through.
CLOCK_EPOCHS = [
    _at(2024, 6, 12, 12, 0, 1),  # odd second
    _at(2024, 2, 29, 23, 59, 59),  # leap day, last second of it
    _at(2024, 3, 1, 0, 0, 0),  # month boundary, midnight
    _at(2023, 12, 31, 23, 59, 58),  # year boundary
    _at(2024, 11, 3, 1, 30, 0),  # the hour the US repeats on DST fall-back
    _at(2025, 1, 1, 0, 0, 0),  # new year
    _at(2024, 7, 4, 9, 15, 33),  # nothing special, odd second
]

PLUGIN_SOURCE = """\
# Generated by flake-detective. Freezes the wall clock at $FD_FREEZE_EPOCH.
# Loaded with -p before conftest and before any test module is imported.
import datetime as _dt
import os
import time as _time

_raw = os.environ.get("FD_FREEZE_EPOCH")

if _raw:
    _e = float(_raw)

    _real_localtime = _time.localtime
    _real_gmtime = _time.gmtime
    _real_strftime = _time.strftime
    _real_asctime = _time.asctime

    _time.time = lambda: _e
    _time.time_ns = lambda: int(_e * 1_000_000_000)
    _time.localtime = lambda t=None: _real_localtime(_e if t is None else t)
    _time.gmtime = lambda t=None: _real_gmtime(_e if t is None else t)
    _time.ctime = lambda t=None: _real_asctime(_real_localtime(_e if t is None else t))
    _time.strftime = (
        lambda f, t=None: _real_strftime(f, _real_localtime(_e) if t is None else t)
    )

    # monotonic and perf_counter are left alone on purpose - see freeze.py.

    _utc_naive = _dt.datetime.fromtimestamp(_e, _dt.timezone.utc).replace(tzinfo=None)

    class _Datetime(_dt.datetime):
        @classmethod
        def now(cls, tz=None):
            return cls.fromtimestamp(_e, tz)

        @classmethod
        def utcnow(cls):
            return cls(*_utc_naive.timetuple()[:6], _utc_naive.microsecond)

        @classmethod
        def today(cls):
            return cls.fromtimestamp(_e)

    class _Date(_dt.date):
        @classmethod
        def today(cls):
            return cls.fromtimestamp(_e)

    _dt.datetime = _Datetime
    _dt.date = _Date
"""

_dir: Path | None = None


def plugin_dir() -> Path:
    """A directory holding the plugin, to be put on PYTHONPATH. Created once, reused."""
    global _dir
    if _dir is None:
        d = Path(tempfile.mkdtemp(prefix="flake-detective-"))
        (d / f"{PLUGIN_NAME}.py").write_text(PLUGIN_SOURCE, encoding="utf-8")
        atexit.register(shutil.rmtree, d, True)
        _dir = d
    return _dir
