"""The pytest plugin injected into every run: what each test actually did, straight from pytest.

The first version read the terminal summary that `-rf` prints - `FAILED path::id - msg` -
and that was wrong in three separate ways, each of which gave a confident wrong answer:

  * **Errors were invisible.** A test whose fixture raised shows up as `ERROR`, not `FAILED`,
    and `-rf` does not print those lines at all. A test was a pass unless proven a failure,
    so a fixture-level order dependence - erroring in every baseline run - appeared nowhere
    in the report, not even as broken.
  * **A test that did not run was a pass.** With `addopts = -x`, the first failure stops the
    run and everything after it never executes. Absence from the failure list read as
    success, so an order-dependent test that happened to sit after a random one came out as
    nondeterministic.
  * **A test id containing " - " vanished.** The summary line separates id from message with
    exactly that, so `test_b[with space - dash]` was cut short, matched no collected test, and
    its failures were never counted anywhere.

So nothing is parsed from text any more. This plugin records, per node id, what pytest itself
reported for setup, call and teardown, and writes it as JSON. A test counts for an arm only in
the runs where it was actually observed to pass or fail.

It also neutralises the options that would make runs incomparable - stopping at the first
failure, stepwise mode, last-failed/failed-first/new-first reordering, and xdist distribution
outside the parallel arm - without discarding the rest of the project's addopts, which it
usually needs (`-p` plugins, markers, import modes).
"""

from __future__ import annotations

PLUGIN_NAME = "fd_observe"

RESULTS_ENV_VAR = "FD_RESULTS_FILE"
ORDER_ENV_VAR = "FD_ORDER_FILE"
EXACT_ENV_VAR = "FD_ORDER_EXACT"
SERIAL_ENV_VAR = "FD_SERIAL"

PLUGIN_SOURCE = """\
# Generated by flake-detective. Records what every test did, from pytest's own reports,
# and writes it to $FD_RESULTS_FILE as JSON. See flake_detective/observe.py.
import json
import os

import pytest

_OUT = os.environ.get("FD_RESULTS_FILE")
_ORDER = os.environ.get("FD_ORDER_FILE")
_EXACT = os.environ.get("FD_ORDER_EXACT") == "1"
_SERIAL = os.environ.get("FD_SERIAL") == "1"

_config = None
_phases = {}  # nodeid -> list of "passed" / "failed" / "error" / "skipped"
_collected = []


def _is_worker(config):
    return config is not None and hasattr(config, "workerinput")


@pytest.hookimpl(tryfirst=True)
def pytest_cmdline_main(config):
    # Every run must execute every selected test, in the order it was handed. Options
    # that stop early or reorder by history would make the runs incomparable, and a
    # test that never ran must not be mistaken for one that passed.
    o = config.option
    for name, value in (
        ("maxfail", 0),  # -x / --exitfirst and --maxfail
        ("stepwise", False),
        ("stepwise_skip", False),
        ("lf", False),
        ("failedfirst", False),
        ("newfirst", False),
    ):
        if hasattr(o, name):
            setattr(o, name, value)
    if _SERIAL and hasattr(o, "numprocesses"):
        # `-n auto` in addopts would distribute the baseline and scramble the order arm.
        o.numprocesses = 0
        o.dist = "no"
        o.tx = []


def pytest_configure(config):
    global _config
    _config = config


@pytest.hookimpl(hookwrapper=True)
def pytest_collection_modifyitems(session, config, items):
    yield
    if not _ORDER:
        return
    with open(_ORDER, encoding="utf-8") as fh:
        wanted = [line.rstrip("\\n") for line in fh if line.strip()]
    rank = {nodeid: i for i, nodeid in enumerate(wanted)}
    keep = sorted((it for it in items if it.nodeid in rank), key=lambda it: rank[it.nodeid])
    extra = [it for it in items if it.nodeid not in rank]
    if _EXACT:
        if extra:
            config.hook.pytest_deselected(items=extra)
        items[:] = keep
    else:
        items[:] = keep + extra


def pytest_collection_finish(session):
    _collected[:] = [it.nodeid for it in session.items]


def pytest_runtest_logreport(report):
    if _is_worker(_config):
        return
    if report.outcome == "rerun":
        # pytest-rerunfailures: the attempt failed and was retried. A retry that passes
        # is exactly the flake being looked for, so the failure is what counts.
        phase = "failed"
    elif report.failed:
        phase = "failed" if report.when == "call" else "error"
    elif report.skipped:
        # An expected failure (xfail) is not a failure; a skip is not an observation.
        phase = "passed" if hasattr(report, "wasxfail") else "skipped"
    elif report.when == "call":
        phase = "passed"
    else:
        return
    _phases.setdefault(report.nodeid, []).append(phase)


@pytest.hookimpl(trylast=True)
def pytest_sessionfinish(session, exitstatus):
    if not _OUT or _is_worker(session.config):
        return
    outcomes = {}
    for nodeid, phases in _phases.items():
        if "error" in phases:
            outcomes[nodeid] = "error"
        elif "failed" in phases:
            outcomes[nodeid] = "failed"
        elif "skipped" in phases:
            outcomes[nodeid] = "skipped"
        elif "passed" in phases:
            outcomes[nodeid] = "passed"
    cfg = session.config
    data = {
        "rootdir": str(getattr(cfg, "rootpath", None) or cfg.rootdir),
        "collected": _collected,
        "outcomes": outcomes,
        "exitstatus": int(exitstatus),
    }
    with open(_OUT, "w", encoding="utf-8") as fh:
        json.dump(data, fh)
"""
